[default]
solc_version = "0.8.15"
src = 'contracts'
out = 'out'
libs = ['lib']
chain_id = 137 
optimizer = true
optimizer_runs = 1000000
fuzz_runs = 10
gas_price = 31000000000
priority_fee = 31000000000

[fulltest]
fuzz_runs = 10000
